[phases.setup]
nixPkgs = ["curl", "git-lfs"]

[phases.build]
cmds = [
  "git lfs install",
  "git lfs pull",
  "pip install -r requirements.txt",
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 300"
