"""
Static INPI Nice Classification positions (partidas) for all 45 classes.
Data structure: POSICIONES[class_num] = [{codigo, partida}, ...]
"""

POSICIONES = {
    1: [
        {"codigo": "010001", "partida": "Productos químicos para uso industrial"},
        {"codigo": "010002", "partida": "Productos químicos para agricultura"},
        {"codigo": "010003", "partida": "Resinas sintéticas y plásticos"},
        {"codigo": "010004", "partida": "Abonos y fertilizantes"},
        {"codigo": "010005", "partida": "Acelerador de procesos químicos"},
        {"codigo": "010006", "partida": "Adhesivos para uso industrial"},
    ],
    2: [
        {"codigo": "020001", "partida": "Pinturas al óleo"},
        {"codigo": "020002", "partida": "Lacas y barnices"},
        {"codigo": "020003", "partida": "Tintas de impresión"},
        {"codigo": "020004", "partida": "Pinturas para construcción"},
        {"codigo": "020005", "partida": "Conservantes de madera"},
    ],
    3: [
        {"codigo": "030001", "partida": "Cosméticos y preparaciones para el cuidado de la piel"},
        {"codigo": "030002", "partida": "Perfumería y fragancias"},
        {"codigo": "030003", "partida": "Productos de higiene personal"},
        {"codigo": "030004", "partida": "Preparaciones de belleza"},
        {"codigo": "030005", "partida": "Productos de limpieza doméstica"},
        {"codigo": "030006", "partida": "Desodorantes y antitranspirantes"},
    ],
    4: [
        {"codigo": "040001", "partida": "Aceites minerales para motores"},
        {"codigo": "040002", "partida": "Combustibles y carburantes"},
        {"codigo": "040003", "partida": "Aceites de lubricación"},
        {"codigo": "040004", "partida": "Grasas lubricantes"},
        {"codigo": "040005", "partida": "Alquitrán y derivados del petróleo"},
    ],
    5: [
        {"codigo": "050001", "partida": "Medicamentos y preparaciones farmacéuticas"},
        {"codigo": "050002", "partida": "Suplementos vitamínicos"},
        {"codigo": "050003", "partida": "Preparaciones para higiene bucal"},
        {"codigo": "050004", "partida": "Productos farmacéuticos para animales"},
        {"codigo": "050005", "partida": "Desinfectantes y antisépticos"},
    ],
    6: [
        {"codigo": "060001", "partida": "Metales comunes en bruto"},
        {"codigo": "060002", "partida": "Alambre de metal"},
        {"codigo": "060003", "partida": "Tuberías metálicas"},
        {"codigo": "060004", "partida": "Herrajes metálicos"},
        {"codigo": "060005", "partida": "Cerraduras y cerrojos metálicos"},
    ],
    7: [
        {"codigo": "070001", "partida": "Máquinas y motores para industria"},
        {"codigo": "070002", "partida": "Bombas hidráulicas"},
        {"codigo": "070003", "partida": "Máquinas para agricultura"},
        {"codigo": "070004", "partida": "Compresores de aire"},
        {"codigo": "070005", "partida": "Turbinas y generadores"},
    ],
    8: [
        {"codigo": "080001", "partida": "Herramientas manuales (hachas, martillos, destornilladores)"},
        {"codigo": "080002", "partida": "Herramientas para carpintería"},
        {"codigo": "080003", "partida": "Herramientas para jardinería"},
        {"codigo": "080004", "partida": "Cuchillos y cortadores manuales"},
        {"codigo": "080005", "partida": "Tenazas y alicates"},
    ],
    9: [
        {"codigo": "090001", "partida": "Aparatos científicos y de medición"},
        {"codigo": "090002", "partida": "Instrumentos ópticos"},
        {"codigo": "090003", "partida": "Computadoras y periféricos"},
        {"codigo": "090004", "partida": "Software de aplicación"},
        {"codigo": "090005", "partida": "Aparatos de fotografía y video"},
        {"codigo": "090006", "partida": "Circuitos integrados y chips"},
    ],
    10: [
        {"codigo": "100001", "partida": "Aparatos y dispositivos médicos"},
        {"codigo": "100002", "partida": "Instrumentos quirúrgicos"},
        {"codigo": "100003", "partida": "Equipos de diagnóstico médico"},
        {"codigo": "100004", "partida": "Prótesis y ortopedia"},
        {"codigo": "100005", "partida": "Equipos de radiología"},
    ],
    11: [
        {"codigo": "110001", "partida": "Aparatos de iluminación (lámparas, luces LED)"},
        {"codigo": "110002", "partida": "Sistemas de calefacción"},
        {"codigo": "110003", "partida": "Equipos de refrigeración"},
        {"codigo": "110004", "partida": "Acondicionadores de aire"},
        {"codigo": "110005", "partida": "Hornos y aparatos de cocción"},
    ],
    12: [
        {"codigo": "120001", "partida": "Automóviles y vehículos de motor"},
        {"codigo": "120002", "partida": "Motocicletas y ciclomotores"},
        {"codigo": "120003", "partida": "Bicicletas y vehículos similares"},
        {"codigo": "120004", "partida": "Remolques y semirremolques"},
        {"codigo": "120005", "partida": "Piezas y accesorios para vehículos"},
    ],
    13: [
        {"codigo": "130001", "partida": "Armas de fuego y municiones"},
        {"codigo": "130002", "partida": "Explosivos y pólvora"},
        {"codigo": "130003", "partida": "Accesorios para armas"},
    ],
    14: [
        {"codigo": "140001", "partida": "Joyas y joyería"},
        {"codigo": "140002", "partida": "Metales preciosos en bruto"},
        {"codigo": "140003", "partida": "Piedras preciosas y semipreciosas"},
        {"codigo": "140004", "partida": "Relojes y cronómetros"},
        {"codigo": "140005", "partida": "Artículos de platería"},
    ],
    15: [
        {"codigo": "150001", "partida": "Instrumentos musicales de cuerda"},
        {"codigo": "150002", "partida": "Instrumentos de viento"},
        {"codigo": "150003", "partida": "Instrumentos de percusión"},
        {"codigo": "150004", "partida": "Instrumentos electrónicos"},
        {"codigo": "150005", "partida": "Accesorios para instrumentos"},
    ],
    16: [
        {"codigo": "160001", "partida": "Papel y cartón para escribir"},
        {"codigo": "160002", "partida": "Productos de imprenta y editorial"},
        {"codigo": "160003", "partida": "Material de encuadernación"},
        {"codigo": "160004", "partida": "Empaques de papel y cartón"},
        {"codigo": "160005", "partida": "Papel de regalo y decorativo"},
    ],
    17: [
        {"codigo": "170001", "partida": "Caucho en bruto y procesado"},
        {"codigo": "170002", "partida": "Productos de goma (llantas, tubos)"},
        {"codigo": "170003", "partida": "Plásticos para moldeo"},
        {"codigo": "170004", "partida": "Tuberías y conductos de plástico"},
        {"codigo": "170005", "partida": "Películas y láminas plásticas"},
    ],
    18: [
        {"codigo": "180001", "partida": "Bolsos y carteras de cuero"},
        {"codigo": "180002", "partida": "Cinturones y accesorios de cuero"},
        {"codigo": "180003", "partida": "Cuero para confección"},
        {"codigo": "180004", "partida": "Maletas y estuches de viaje"},
        {"codigo": "180005", "partida": "Articulos de marroquinería"},
    ],
    19: [
        {"codigo": "190001", "partida": "Materiales para construcción (ladrillos, baldosas)"},
        {"codigo": "190002", "partida": "Cemento y hormigón"},
        {"codigo": "190003", "partida": "Tuberías para construcción"},
        {"codigo": "190004", "partida": "Aislantes y materiales refractarios"},
        {"codigo": "190005", "partida": "Vidrios para construcción"},
    ],
    20: [
        {"codigo": "200001", "partida": "Muebles para el hogar"},
        {"codigo": "200002", "partida": "Muebles de oficina"},
        {"codigo": "200003", "partida": "Camas y colchones"},
        {"codigo": "200004", "partida": "Armarios y estanterías"},
        {"codigo": "200005", "partida": "Artículos decorativos para el hogar"},
    ],
    21: [
        {"codigo": "210001", "partida": "Utensilios de cocina"},
        {"codigo": "210002", "partida": "Vajilla y cristalería"},
        {"codigo": "210003", "partida": "Ollas y sartenes"},
        {"codigo": "210004", "partida": "Cubiertos de mesa"},
        {"codigo": "210005", "partida": "Bandejas y fuentes"},
    ],
    22: [
        {"codigo": "220001", "partida": "Cuerdas y cordeles"},
        {"codigo": "220002", "partida": "Fibras naturales procesadas"},
        {"codigo": "220003", "partida": "Redes y mallas"},
        {"codigo": "220004", "partida": "Arpilleras y telas burdas"},
        {"codigo": "220005", "partida": "Lonas y telas impermeables"},
    ],
    23: [
        {"codigo": "230001", "partida": "Hilos de algodón para coser"},
        {"codigo": "230002", "partida": "Hilos de lana para tejido"},
        {"codigo": "230003", "partida": "Hilos sintéticos"},
        {"codigo": "230004", "partida": "Hilos de seda"},
        {"codigo": "230005", "partida": "Cordones y cintas textiles"},
    ],
    24: [
        {"codigo": "240001", "partida": "Telas de algodón"},
        {"codigo": "240002", "partida": "Telas de lana"},
        {"codigo": "240003", "partida": "Telas sintéticas"},
        {"codigo": "240004", "partida": "Telas estampadas"},
        {"codigo": "240005", "partida": "Tejidos especializados"},
    ],
    25: [
        {"codigo": "250001", "partida": "Ropa interior"},
        {"codigo": "250002", "partida": "Camisas y blusas"},
        {"codigo": "250003", "partida": "Pantalones y polleras"},
        {"codigo": "250004", "partida": "Abrigos y chaquetas"},
        {"codigo": "250005", "partida": "Vestidos y trajes"},
        {"codigo": "250006", "partida": "Calzado (zapatos, botas, sandalias)"},
        {"codigo": "250007", "partida": "Accesorios de vestir"},
    ],
    26: [
        {"codigo": "260001", "partida": "Encajes y adornos textiles"},
        {"codigo": "260002", "partida": "Bordados y trabajos manuales"},
        {"codigo": "260003", "partida": "Cintas y galones"},
        {"codigo": "260004", "partida": "Aplicaciones y parches"},
    ],
    27: [
        {"codigo": "270001", "partida": "Alfombras y tapetes"},
        {"codigo": "270002", "partida": "Pieles y cueros para alfombras"},
        {"codigo": "270003", "partida": "Tapetes para baño"},
        {"codigo": "270004", "partida": "Alfombras orientales"},
    ],
    28: [
        {"codigo": "280001", "partida": "Juegos de mesa (ajedrez, damas)"},
        {"codigo": "280002", "partida": "Juguetes infantiles"},
        {"codigo": "280003", "partida": "Peluches y muñecos"},
        {"codigo": "280004", "partida": "Juegos de construcción"},
        {"codigo": "280005", "partida": "Equipos deportivos para juegos"},
    ],
    29: [
        {"codigo": "290001", "partida": "Carnes frescas"},
        {"codigo": "290002", "partida": "Embutidos y conservas de carne"},
        {"codigo": "290003", "partida": "Aves de corral"},
        {"codigo": "290004", "partida": "Productos pesqueros procesados"},
        {"codigo": "290005", "partida": "Productos lácteos"},
    ],
    30: [
        {"codigo": "300001", "partida": "Café y sucedáneos"},
        {"codigo": "300002", "partida": "Té e infusiones"},
        {"codigo": "300003", "partida": "Chocolate y cacao"},
        {"codigo": "300004", "partida": "Azúcar y miel"},
        {"codigo": "300005", "partida": "Pan y productos de panadería"},
        {"codigo": "300006", "partida": "Repostería y confitería"},
    ],
    31: [
        {"codigo": "310001", "partida": "Granos y cereales"},
        {"codigo": "310002", "partida": "Frutas y verduras frescas"},
        {"codigo": "310003", "partida": "Semillas y plantas vivas"},
        {"codigo": "310004", "partida": "Alimentos para animales"},
        {"codigo": "310005", "partida": "Flores y plantas ornamentales"},
    ],
    32: [
        {"codigo": "320001", "partida": "Cervezas"},
        {"codigo": "320002", "partida": "Aguas minerales y refrescos"},
        {"codigo": "320003", "partida": "Bebidas sin alcohol"},
        {"codigo": "320004", "partida": "Zumos y néctares"},
        {"codigo": "320005", "partida": "Bebidas energéticas"},
    ],
    33: [
        {"codigo": "330001", "partida": "Vinos y licores"},
        {"codigo": "330002", "partida": "Destilados y bebidas espirituosas"},
        {"codigo": "330003", "partida": "Champagnes y espumantes"},
        {"codigo": "330004", "partida": "Bebidas alcohólicas diversas"},
    ],
    34: [
        {"codigo": "340001", "partida": "Tabaco en rama y procesado"},
        {"codigo": "340002", "partida": "Cigarrillos"},
        {"codigo": "340003", "partida": "Puros y cigarritos"},
        {"codigo": "340004", "partida": "Accesorios para fumadores"},
    ],
    35: [
        {"codigo": "350001", "partida": "Publicidad y material publicitario"},
        {"codigo": "350002", "partida": "Gestión comercial de empresas"},
        {"codigo": "350003", "partida": "Marketing y promoción"},
        {"codigo": "350004", "partida": "Servicios de venta al por menor"},
        {"codigo": "350005", "partida": "Publicidad online"},
        {"codigo": "350006", "partida": "Asesoramiento empresarial"},
    ],
    36: [
        {"codigo": "360001", "partida": "Servicios de seguros"},
        {"codigo": "360002", "partida": "Servicios de finanzas"},
        {"codigo": "360003", "partida": "Servicios de hipoteca"},
        {"codigo": "360004", "partida": "Servicios bancarios"},
        {"codigo": "360005", "partida": "Servicios de inversión"},
    ],
    37: [
        {"codigo": "370001", "partida": "Construcción y reparación de edificios"},
        {"codigo": "370002", "partida": "Reparación de equipos"},
        {"codigo": "370003", "partida": "Servicios de fontanería y electricidad"},
        {"codigo": "370004", "partida": "Instalación de sistemas"},
        {"codigo": "370005", "partida": "Mantenimiento de maquinaria"},
    ],
    38: [
        {"codigo": "380001", "partida": "Telecomunicaciones por teléfono"},
        {"codigo": "380002", "partida": "Servicios de internet"},
        {"codigo": "380003", "partida": "Servicios de radiocomunicaciones"},
        {"codigo": "380004", "partida": "Retransmisión de datos"},
        {"codigo": "380005", "partida": "Servicios de telecomunicaciones inalámbricas"},
    ],
    39: [
        {"codigo": "390001", "partida": "Transporte de mercancías"},
        {"codigo": "390002", "partida": "Transporte de pasajeros"},
        {"codigo": "390003", "partida": "Transporte aéreo"},
        {"codigo": "390004", "partida": "Transporte marítimo"},
        {"codigo": "390005", "partida": "Servicios de almacenamiento"},
    ],
    40: [
        {"codigo": "400001", "partida": "Transformación de materiales"},
        {"codigo": "400002", "partida": "Tratamiento de residuos"},
        {"codigo": "400003", "partida": "Purificación de agua"},
        {"codigo": "400004", "partida": "Servicios de teñido y acabado"},
    ],
    41: [
        {"codigo": "410001", "partida": "Educación y formación"},
        {"codigo": "410002", "partida": "Servicios de entretenimiento"},
        {"codigo": "410003", "partida": "Organización de eventos deportivos"},
        {"codigo": "410004", "partida": "Servicios de cine y teatro"},
        {"codigo": "410005", "partida": "Publicación de libros"},
    ],
    42: [
        {"codigo": "420001", "partida": "Servicios científicos y de investigación"},
        {"codigo": "420002", "partida": "Servicios de diseño y desarrollo"},
        {"codigo": "420003", "partida": "Servicios de análisis y testing"},
        {"codigo": "420004", "partida": "Servicios de programación"},
        {"codigo": "420005", "partida": "Servicios de consultoría técnica"},
    ],
    43: [
        {"codigo": "430001", "partida": "Servicios de restaurante"},
        {"codigo": "430002", "partida": "Servicios de bar y bebidas"},
        {"codigo": "430003", "partida": "Servicios de hogar y alojamiento"},
        {"codigo": "430004", "partida": "Servicios de hotel"},
        {"codigo": "430005", "partida": "Servicios de camping"},
    ],
    44: [
        {"codigo": "440001", "partida": "Servicios médicos"},
        {"codigo": "440002", "partida": "Servicios de dentista"},
        {"codigo": "440003", "partida": "Servicios de veterinaria"},
        {"codigo": "440004", "partida": "Servicios de psicología"},
        {"codigo": "440005", "partida": "Servicios de fisioterapia"},
    ],
    45: [
        {"codigo": "450001", "partida": "Servicios jurídicos"},
        {"codigo": "450002", "partida": "Servicios de seguridad"},
        {"codigo": "450003", "partida": "Servicios de vigilancia"},
        {"codigo": "450004", "partida": "Servicios de custodia"},
        {"codigo": "450005", "partida": "Servicios de arbitraje y mediación"},
    ],
}

assert len(POSICIONES) == 45
for i in range(1, 46):
    assert i in POSICIONES
